name: pos_flutter
description: Modern Point of Sale System for Vehicle Management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Navigation
  go_router: ^12.1.1
  
  # Image & File Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  file_picker: ^6.1.1
  
  # PDF & Documents
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Charts & Analytics
  fl_chart: ^0.64.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  
  # Authentication
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700